apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-facturacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-facturacion
  template:
    metadata:
      labels:
        app: microservicio-facturacion
    spec:
      containers:
        - name: facturacion
          image: astarto/microservicio-facturacion
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/facturaciondb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: facturacion-service
spec:
  selector:
    app: microservicio-facturacion
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
