apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-central
  template:
    metadata:
      labels:
        app: microservicio-central
    spec:
      containers:
        - name: central
          image: astarto/microservicio-central
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/centraldb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: central-service
spec:
  selector:
    app: microservicio-central
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
